DROP VIEW IF EXISTS P02_Les_gagnants;
DROP VIEW IF EXISTS P02_Nomination_film;
DROP VIEW IF EXISTS P02_PrixByCeremonie;

DROP TABLE IF EXISTS P02_NOMINATION;
DROP TABLE IF EXISTS P02_CEREMONIE;
DROP TABLE IF EXISTS P02_RECOMPENSE;
DROP TABLE IF EXISTS P02_FILM;
DROP TABLE IF EXISTS P02_INDIVIDU;


