DROP VIEW IF EXISTS  P02_Les_gagnants,P02_Nomination_film,P02_PrixByCeremonie;
DROP PROCEDURE() IF EXISTS  P02_RenommerIndividu;
DROP FUNCTION() IF EXISTS  P02_Nombre_Gagne;
DROP TYPE IF EXISTS P02_recompenseObjet;
DROP FUNCTION() IF EXISTS  P02_RecompenseOfCeremonie;
DROP TRIGGER IF EXISTS  P02_Majuscule ON P02_individu;
DROP TABLE IF EXISTS P02_NOMINATION,P02_FILM,P02_INDIVIDU,P02_RECOMPENSE,P02_CEREMONIE;
